export interface NoteAuthor {
  id: string;
  name: string;
}

export interface Note {
  id: string;
  seq: number;
  sourceId: string;
  author: NoteAuthor;
  parent: string | null;
  body: string;
  highlights: Highlight[];
  createdAt: string;
  editedAt: string | null;
  deletedAt: string | null;
  version: number;
}

export interface PdfRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export type HighlightAnchor =
  | { kind: "epub-cfi"; value: string }
  | { kind: "pdf-text"; page: number; rects: PdfRect[] };

export interface QuoteSelector {
  type: "TextQuoteSelector";
  exact: string;
  prefix: string;
  suffix: string;
}

export interface Highlight {
  id: string;
  sourceId: string;
  anchor: HighlightAnchor;
  quote: QuoteSelector;
  createdAt: string;
}

export function epubAnchor(value: string): HighlightAnchor {
  return { kind: "epub-cfi", value };
}

export function pdfAnchor(page: number, rects: PdfRect[]): HighlightAnchor {
  return { kind: "pdf-text", page, rects };
}

// An offline-durable, idempotent mutation. `opId` and `noteId` are generated by
// the client (ULIDs) so a note has a stable identity before the server ever
// acknowledges it — that is what makes replies/edits/deletes safe to author and
// replay while disconnected. `seq` is never carried here: it stays
// server-authoritative and is assigned when the op is first applied.
export type NoteOp =
  | {
      opId: string;
      kind: "add";
      noteId: string;
      sourceId: string;
      body: string;
      highlights: Highlight[];
      createdAt: string;
    }
  | {
      opId: string;
      kind: "reply";
      noteId: string;
      sourceId: string;
      parent: string;
      body: string;
      createdAt: string;
    }
  | { opId: string; kind: "edit"; noteId: string; body: string; at: string }
  | { opId: string; kind: "remove"; noteId: string; at: string }
  | { opId: string; kind: "rebind"; noteId: string; highlightId: string; anchor: HighlightAnchor };

export interface RejectedOp {
  opId: string;
  // Why the server refused the op. These are surfaced to the author rather than
  // silently dropped, so authored content never disappears without explanation.
  reason: "forbidden" | "gone";
}

export interface ApplyOpsResult {
  appliedOpIds: string[];
  rejectedOps: RejectedOp[];
}
