export interface NoteAuthor {
  id: string;
  name: string;
}

export interface Note {
  id: string;
  seq: number;
  sourceId: string;
  author: NoteAuthor;
  parent: string | null;
  body: string;
  highlights: Highlight[];
  createdAt: string;
  editedAt: string | null;
  deletedAt: string | null;
  version: number;
  // Free-form markers on a note. Optional so notes persisted before tags
  // existed (and the DO snapshots holding them) keep deserializing untouched.
  tags?: string[];
}

// The one tag the app gives special meaning: a highlight is a note whose body
// is just the quoted passage, surfaced with a "highlighted" verb instead of
// "posted". Kept as a tag (not a distinct note kind) so it flows through the
// existing note machinery unchanged.
export const HIGHLIGHT_TAG = "highlight";

export function isHighlight(note: Note): boolean {
  return note.tags?.includes(HIGHLIGHT_TAG) ?? false;
}

export interface PdfRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export type HighlightAnchor =
  | { kind: "epub-cfi"; value: string }
  | { kind: "pdf-text"; page: number; rects: PdfRect[] };

export interface QuoteSelector {
  type: "TextQuoteSelector";
  exact: string;
  prefix: string;
  suffix: string;
}

export interface Highlight {
  id: string;
  sourceId: string;
  anchor: HighlightAnchor;
  quote: QuoteSelector;
  createdAt: string;
}

export function epubAnchor(value: string): HighlightAnchor {
  return { kind: "epub-cfi", value };
}

export function pdfAnchor(page: number, rects: PdfRect[]): HighlightAnchor {
  return { kind: "pdf-text", page, rects };
}

// An offline-durable, idempotent mutation. `opId` and `noteId` are generated by
// the client (ULIDs) so a note has a stable identity before the server ever
// acknowledges it — that is what makes replies/edits/deletes safe to author and
// replay while disconnected. `seq` is never carried here: it stays
// server-authoritative and is assigned when the op is first applied.
export type NoteOp =
  | {
      opId: string;
      kind: "add";
      noteId: string;
      sourceId: string;
      body: string;
      highlights: Highlight[];
      createdAt: string;
      tags?: string[];
    }
  | {
      opId: string;
      kind: "reply";
      noteId: string;
      sourceId: string;
      parent: string;
      body: string;
      createdAt: string;
    }
  | { opId: string; kind: "edit"; noteId: string; body: string; at: string }
  | { opId: string; kind: "remove"; noteId: string; at: string }
  | { opId: string; kind: "rebind"; noteId: string; highlightId: string; anchor: HighlightAnchor };

export const NoteRejectionReason = { Forbidden: "forbidden", Gone: "gone" } as const;

export type NoteRejectionReason = (typeof NoteRejectionReason)[keyof typeof NoteRejectionReason];

export interface RejectedOp {
  opId: string;
  // Why the server refused the op. These are surfaced to the author rather than
  // silently dropped, so authored content never disappears without explanation.
  reason: NoteRejectionReason;
}

export interface ApplyOpsResult {
  appliedOpIds: string[];
  rejectedOps: RejectedOp[];
}
